version: "3.8"
services: # app components like ui , logs , db
  ashu-ui-service:
    image: sankar-webui:version$BUILD_NUMBER
    build:
      context: . # location of dockerfile
      dockerfile: Dockerfile # name of Dockerfile
    container_name: sankar-web-c2 # name of container
    ports:
      - 4568:80 # you can use 1024-5000 range
