apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sankarlb1
  name: sankarlb1 # change name of service
  namespace: sankar-space # adding namespace 
spec:
  ports:
  - name: 4567-80
    port: 4567
    protocol: TCP
    targetPort: 80
  selector: # you have match label with pod template
   app: sankar-dep1 # update label of pod template section
  type: NodePort
status:
  loadBalancer: {}
